language: python

env:
  - TOXENV=py26-dj16-cms30-sqlite
  - TOXENV=py27-dj16-cms30-sqlite
  - TOXENV=py27-dj17-cms30-sqlite
  - TOXENV=py27-dj17-cms30-mysql
  - TOXENV=py27-dj17-cms30-postgres
  - TOXENV=py26-dj16-cms31-sqlite
  - TOXENV=py27-dj16-cms31-sqlite
  - TOXENV=py27-dj17-cms31-sqlite
  - TOXENV=py27-dj17-cms31-mysql
  - TOXENV=py27-dj17-cms31-postgres
  - TOX_ENV=pep8

matrix:
  allow_failures:
    - env: TOX_ENV=pep8

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e $TOXENV

after_success:
  - coveralls

notifications:
  webhooks: http://addons.us-iad-rs.aldryn.io/en/travis-endpoint/
