name: Jobs
package-name: aldryn-jobs
url: https://github.com/aldryn/aldryn-jobs
author:
  name: Divio AG
  url: https://www.divio.ch
installed-apps:
  - absolute
  - aldryn_jobs
  - emailit
  - hvad
  - standard_form
version: 0.0.9
description: Publish job offers on your site
license:
  name: BSD
  text: !literal-include LICENSE.txt
